### ISSUE TITLE
Dropdowns

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#122]
Switch to using dropdowns for voting and priv actions

Need to create a handler to generate

**Comment by 3061LRTAGSPKJMORMRT** [comment]
Already did this in the pr

**Comment by inno14** [comment]
Seems a nice and difficult idea :)
![Screenshot_20220112-000425_Discord](https://user-images.githubusercontent.com/83353462/149001630-375094d9-078e-4669-ba2f-10d1fd3eeac4.jpg)

**Comment by inno14** [comment]
Also if you don't prefer to do this then make a cancel command to cancel the action for every role
