### ISSUE TITLE
Gr conversion 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#127]
Gr should be converted into ft but he didn't get into ft.
Sk stabbed grs' target and they didn't get a convert
![Screenshot_20210703-210428_Discord](https://user-images.githubusercontent.com/83353462/124359888-7b553280-dc44-11eb-9fde-85efe013bd2f.jpg)
![Screenshot_20210703-210745_Discord](https://user-images.githubusercontent.com/83353462/124359890-7f815000-dc44-11eb-8136-65abc9162542.jpg)

**Comment by inno14** [comment]
![Screenshot_20210703-212211_Discord](https://user-images.githubusercontent.com/83353462/124359958-c2432800-dc44-11eb-8851-d0013028ed5c.jpg)
 
![Screenshot_20210703-212204_Discord](https://user-images.githubusercontent.com/83353462/124359960-c707dc00-dc44-11eb-970c-aa35892ddb18.jpg)

**Comment by Hackante** [comment]
Role not coded yet
