### ISSUE TITLE
Ft cards

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#128]
2 was a converted ft and was giving cards to 1 & 4 for the first time. 
Other fts already gave them cards already but he was unable to do so.
![Screenshot_20210703-212251_Discord](https://user-images.githubusercontent.com/83353462/124360000-033b3c80-dc45-11eb-8ee3-e629e85d30df.jpg)

**Comment by thewilloftheshadow** [comment]
Isn't ft a one-only role, can only have one of them in a game?

**Comment by inno14** [comment]
There can be more than 1 ft in game. 
The only roles which can be 1 are cupid, Jailer, president & sect leader .

**Comment by thewilloftheshadow** [comment]
Ah ok, I didn't know that

**Comment by Gorott** [comment]
U sure they didn't already get cards?
