### ISSUE TITLE
Bye didn't delete channels

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#147]
![Screenshot_20210710-003131_Discord](https://user-images.githubusercontent.com/83353462/125124741-32a2eb00-e116-11eb-97f1-116e3726047e.jpg)

**Comment by Gmo666** [comment]
Bye isn't supposed to delete channels, reset is supposed to

**Comment by thewilloftheshadow** [comment]
No, channels are cleared on +bye. +reset only does the database and perms

**Comment by inno14** [comment]
Channels didn't get a delete yet so this bug still exists @thewilloftheshadow 
![Screenshot_20210714-141854_Discord](https://user-images.githubusercontent.com/83353462/125592987-7d400d51-242b-4936-aa3a-f472232cf439.jpg)
