### ISSUE TITLE
Hacker

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#153]
Name: Hacker
Icon: A shadow in a purple cloak on a computer screen
Aura: Unknown
Team: Solo
Replaces: Solo Killer
Victory Condition: Last player alive

Ability:
Hack (2 uses per night)
Select a player to hack. If a player is hacked once, their role will be revealed to you. If a player is hacked twice, they will die. You cannot hack the same player twice in one night.

Speak Disable (1-use, at night)
You can mute a hacked player at night, muting them for the day and they cannot vote either. 

In-game description:
You can hack two players per night. If a player is hacked once, you will know their role. If a player is hacked twice, they will die. You can also mute a hacked player, making them not able to talk or vote for the day.

Interactions:
- You receive a hacked player's role or kill a player that is hacked twice at the end of the night.
- A hacked player does not know they are hacked.
- Mute functions exactly like GG except the village does not know they are muted.
- The first hack pierces protection but the second attack does not,

Pros:
- You can receive information of two players in one night, and they can be killed at will in the next night.
- The mute could cause confusion as the village does not know of the mute.
- Only you know the information and not even the hacked players know they are hacked, so they do not know if they are at risk of dying to Hacker

Cons:
- You cannot kill a player in 1 night.
- Special Disable can only be used if you had hacked the player in a previous night.
- You can only kill a maximum of 2 players per night, no matter how many are hacked.

**Comment by Gmo666** [comment]
Oh and I'll add something, if hacker's second hack (aka the attack) is blocked by a protector, this happens:
Doc: Doc saves target, target is still hacked once
BG: BG saves target and gets hacked instead (so Hacker knows his role)
TG: TG saves target and dies of injuries. (This happens even if Hacker directly hacks TG)
BH/Witch/Forger/Jailer: Same as Doc

**Comment by thewilloftheshadow** [comment]
Update?
