### ISSUE TITLE
getEmoji()

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#154]
Every spot in the bot that uses a custom emoji (non-unicode) needs to be replaced with a getEmoji function instead

**Comment by sampadap03** [comment]
@thewilloftheshadow can you clarify more on this? Do we have to create a custom function?

**Comment by thewilloftheshadow** [comment]
In the config, there is a getEmoji function. Its available both of the following ways:

```
const { getEmoji } = require("../config")
getEmoji("muted", client)
```
```
const { fn } = require("../config")
fn.getEmoji("muted", client
```

Currently, we just use the raw form of emojis directly in the code itself: `<:muted:776460712008351776>`
What I want to do is replace that with this: `getEmoji("muted", client)`

So a string would now look like this:
```
message.channel.send(`${getEmoji("muted", client)} **User** was muted!`)
```
