### ISSUE TITLE
Jailed perms mess ~~maybe with hacker~~

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#179]
![Screenshot_20210720-212831_Discord](https://user-images.githubusercontent.com/83353462/126357113-4dafcd25-c312-48bd-84fe-215b63cf8420.jpg)
He couldn't see the channel and couldn't send messages

**Comment by sampadap03** [comment]
@inno14 can you explain?

**Comment by inno14** [comment]
> @inno14 can you explain?

@sampadap03 jailed person got no perms to see channel
