### ISSUE TITLE
`+win tie ` not working 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#183]
![Screenshot_20210725-214229_Discord](https://user-images.githubusercontent.com/83353462/126905895-38f1cbc0-fdaa-4c42-8951-a6f42ee87278.jpg)
People didn't get up the xp and as well bot didn't say `Done`.

**Comment by thewilloftheshadow** [comment]
Will be fixed by https://github.com/wwosimulation/tracker/issues/39
