### ISSUE TITLE
Dreamcatcher

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#192]
Name: Dreamcatcher/DC
Icon: Made by @Stimmicus | Master Librarian 
Aura: Unknown
Team: Solo
Replaces: Solo killers
Win Condition: Last alive

Ability: DC can hypnotize one person in the day. When nighttime comes, the role of the hypnotized player will be revealed to DC, and DC takes complete control of that person's abilities for that night. Any kills while controlled will be written as such: "The Dreamcatcher compelled {role} to kill {player}. When the night ends, the player that was controlled is attacked by DC. DC cannot hypnotize the player that was hypnotized last night. If the hypnotized player is attacked and survives, they cannot vote that day.

In-Game Description: You can select a player every day. At night, this person will be under your control, and you can use their abilities. At the end of the night, you attack the person that you are controlling.

Pros:
+ Can control another player, leading to more info, extra kills, or misprotection.
+ Even if the player you hypnotize is protected, they were still roleblocked.
+ Harder to defend against.

Cons:
- Can't kill first night.
- You can't change your mind at night.
- If you compel somebody to kill, everybody will know who is hypnotized.

Interactions:
Wolves cannot kill you.
Hypnotizing a cupid does not reveal their couple, and hypnotizing a lover does not reveal their lover.
Hypnotizing a wolf, medium, or jailer does not gain access to their respective chats.
When attacking a tg, DC will not kill them that night. Tg will know the DC's role but cannot protect any other players. If attacked by a wolf in this time, they will know that info as well. They will die the following night.
Protection such as shields and traps that are continuously applied will completely nullify hypnosis.

**Comment by Garcello822** [comment]
let me know in dms if you need me to send the icon

**Comment by sampadap03** [comment]
@Garcello822 you can attach here as well
