### ISSUE TITLE
People not dying after bomber death

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#193]
Bomber died on night 2 by poison of witch. They bombed 5 6 7 on night 1. But none of them died. So i killed them manually. 
![Screenshot_20210728-155005_Discord](https://user-images.githubusercontent.com/83353462/127306706-fe81c2b8-1815-4427-b548-c5ef5b505862.jpg)

**Comment by 3061LRTAGSPKJMORMRT** [comment]
This should be fixed since the bot's code has been rewritten
