### ISSUE TITLE
Bot doesn't give gr a new channel on his target death 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#204]
![Screenshot_20210729-150735_Discord](https://user-images.githubusercontent.com/83353462/127469412-205b953c-0f57-4324-86b8-a2841990de13.jpg)

Gr doesn't get a new channel when his target died.

**Comment by Gmo666** [comment]
bot literally does nothing

**Comment by Hackante** [comment]
Role isn't coded yet
