### ISSUE TITLE
+nmanual didn't remove the role 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#206]
![Screenshot_20210729-152119_Discord](https://user-images.githubusercontent.com/83353462/127471373-78e5b266-2394-4878-9602-4f5fd3efee39.jpg)
![Screenshot_20210729-152106_Discord](https://user-images.githubusercontent.com/83353462/127471424-7456bae3-adcc-4aa0-becb-0e6e5c450c04.jpg)
 
We used up nmanual but the bot didn't remove the role from 5.

**Comment by FinnyMarigold58** [comment]
Duplicate of #241
