### ISSUE TITLE
Redirect shadow votes 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#210]
Idk if it is possible or not but just wanted to say
How about creating a new channel with name #shadow-votes or something like that then whenever shadow-wolf activates shadow then votes are redirected there?

Also if is possible then maybe when votes go to #shadow-votes then it says `5 ww has voted 3` so that narrator doesn't forget to count vote of wolves double .

**Comment by 3061LRTAGSPKJMORMRT** [comment]
The bot now hides the vote from the narrator as well so
