### ISSUE TITLE
Update the response 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#211]
![Screenshot_20210729-174536_Discord](https://user-images.githubusercontent.com/83353462/127492961-39b23596-0c9d-4f31-beb3-dbcf1cb1a900.jpg)
This message should also tell us which gamemode is being played whether quick, sandbox or random

**Comment by sampadap03** [comment]
yes

**Comment by FinnyMarigold58** [comment]
We would have to add another arg to the start command or add the message to the srole command.

**Comment by thewilloftheshadow** [comment]
The first argument of srole is the game mode
