### ISSUE TITLE
Dev Tracker

### ISSUE THREAD

**Issue by sampadap03** [wwosimulation/tracker#219]
Add a comment of what you are working on:

Each comment consist of 

1. Name
2. Which feature working on
3. Issues focused on
4. PRs and open branches if any

Edit your comment every time you change something of those.

**Comment by Hackante** [comment]
1. Hackante
2. Leader board 
3. [Issue#45](https://github.com/wwosimulation/tracker/issues/45) 
4. Work tree [leaderboard](https://github.com/wwosimulation/Narrator-bot/tree/leaderboard/)

**Comment by thewilloftheshadow** [comment]
# Shadow's Assigned Tasks

## Currently working on:
https://github.com/wwosimulation/tracker/issues/117
Localization Management
Setting up better CI

## In Design
https://github.com/wwosimulation/tracker/issues/122
https://github.com/wwosimulation/tracker/issues/170

## On Hold:
https://github.com/wwosimulation/tracker/issues/39
https://github.com/wwosimulation/tracker/issues/122

**Comment by sampadap03** [comment]
1. Aqua
2. Error responses
3. https://github.com/wwosimulation/tracker/issues/212, https://github.com/wwosimulation/tracker/issues/151
4. [error-responses](https://github.com/wwosimulation/Narrator-bot/tree/error-responses)

**Comment by Gorott** [comment]
1. Gorotiepie
2. Dreamcatcher
3. [https://github.com/wwosimulation/tracker/issues/219](#219)
4. [https://github.com/wwosimulation/Narrator-bot/tree/Dreamcatcher](Dreamcatcher)

**Comment by inno14** [comment]
# Inno's Assigned Tasks
None atm

# Recently Done
#github.com/wwosimulation/config/pull/22

**Comment by FinnyMarigold58** [comment]
## Finny's Assigned Tasks

### Currently working on bug fixes on branch [more-bug-fixes](https://github.com/wwosimulation/Narrator-bot/tree/more-bug-fixes)

 Solokillers and villagekillers fix related to #218 

- [ ] Fixed

Stop spectators from voting

No tracker issue

- [ ] Added

**Comment by thewilloftheshadow** [comment]
Superseded by https://github.com/orgs/wwosimulation/projects/2, see the readme of this repo for instructions
