### ISSUE TITLE
Sheriff can see himself as suspect on watching someone who died the day

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#228]
![Screenshot_20210804-224915_Discord](https://user-images.githubusercontent.com/83353462/128226074-4968131d-3905-41b6-9203-22da39d8f28d.jpg)

**Comment by Gmo666** [comment]
Sheriff: Oh no, the person I was watching got killed
Sheriff: Hm I suspect 4 and... myself as the killer.

**Comment by thewilloftheshadow** [comment]
LMFAO that’s a funny bug

**Comment by 3061LRTAGSPKJMORMRT** [comment]
This should be fixed since the bot's code has been rewritten
