### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#230]
List of players and their role wasn't removed from `+playerinfo ` when i used `+reset `.
But it was removed when i deleted the channels manually.
![Screenshot_20210804-231457_Discord](https://user-images.githubusercontent.com/83353462/128229338-752c7b59-0c9f-40a4-b15d-f32e7c10a496.jpg)
![Screenshot_20210804-231504_Discord](https://user-images.githubusercontent.com/83353462/128229348-3146f487-a3d1-4cb0-a262-82dcb963a129.jpg)

**Comment by FinnyMarigold58** [comment]
@inno14 Were the players in the server when you did the command and did that have access to the priv chats when you did the cmd?

**Comment by thewilloftheshadow** [comment]
@inno14

**Comment by inno14** [comment]
>  Were the players in the server when you did the command 
Yes
> did that have access to the priv chats when you did the cmd?
Yes

**Comment by FinnyMarigold58** [comment]
Not a bug, playerinfo command only goes off of the channel perms that the players have

**Comment by FinnyMarigold58** [comment]
Extra note: when you do playerinfo it sets the players role in the database

**Comment by Gmo666** [comment]
you're not supposed to do +reset when there are players in the server?

**Comment by inno14** [comment]
> you're not supposed to do +reset when there are players in the server?

I was testing something
