### ISSUE TITLE
Alive role doesn't get removed 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#243]
People who died via bot like bot kill them or i use suicide command then they eventually get the dead role but they don't lose the alive role.

**Comment by inno14** [comment]
When 2 died from the tag by jww 
-> 
![Screenshot_20210821-160030_Discord](https://user-images.githubusercontent.com/83353462/130319524-cd37403d-e5dd-4de1-97d8-e1ce20f436a2.jpg)


When 5 died from the snap of illu 
-> 
![Screenshot_20210821-160542_Discord](https://user-images.githubusercontent.com/83353462/130319538-e7c14aeb-6b37-47ea-a05a-7dfbc90fcc65.jpg)

3 dies after i used suicide command 
-> 
![Screenshot_20210821-160556_Discord](https://user-images.githubusercontent.com/83353462/130319559-cf998b34-a553-44ea-bd54-2159787f4fb2.jpg)

**Comment by inno14** [comment]
Btw it was the case with everyone except yolo and 5 ~~when they died on n1~~ ,  i dont have ss for 4/meepz.

**Comment by Gorott** [comment]
Works
