### ISSUE TITLE
Tough Guy not getting one of the info when two people attacked him

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#244]
On n2, tg got attacked by illu and ww both but he was able to see only ww and not illu.

**Comment by inno14** [comment]
![Screenshot_20210821-163629_Discord](https://user-images.githubusercontent.com/83353462/130319826-1f6591ee-be08-4ec8-b6f2-e4c85cc24c7f.jpg)

**Comment by inno14** [comment]
![Screenshot_20210821-163657_Discord](https://user-images.githubusercontent.com/83353462/130319838-e596c4d8-55c0-452d-a7af-d4893210ea3e.jpg)

**Comment by inno14** [comment]
![Screenshot_20210821-163733_Discord](https://user-images.githubusercontent.com/83353462/130319853-db29a58d-e232-4e55-aedd-f4c4e379423e.jpg)

**Comment by 3061LRTAGSPKJMORMRT** [comment]
This should be fixed since the bot's code has been rewritten
