### ISSUE TITLE
Say command not working 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#246]
![Screenshot_20210821-164042_Discord](https://user-images.githubusercontent.com/83353462/130319929-b40d7278-08aa-4aa4-8262-67cde4e086a9.jpg)
![Screenshot_20210821-164124_Discord](https://user-images.githubusercontent.com/83353462/130319937-8a41b52b-3779-414e-9069-b77b331ad46a.jpg)

**Comment by thewilloftheshadow** [comment]
It thought 4 was the ID of a message and then it couldn’t find the message. NAB
