### ISSUE TITLE
Saying message 4 times instead once

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#249]
When cursed was converted then bot sent 4 messages 
![Screenshot_20210822-134939_Discord](https://user-images.githubusercontent.com/83353462/130347959-580533c4-6400-4721-acfa-fed5bc8c58e0.jpg)

**Comment by thewilloftheshadow** [comment]
I don't see 4 messages??

**Comment by inno14** [comment]
Oops wrong ss 😂
![Screenshot_20210822-132953_Discord](https://user-images.githubusercontent.com/83353462/130390818-c634af4f-4047-46ae-8274-5fb4b6db8ad7.jpg)
