### ISSUE TITLE
manual not working 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#256]
![Screenshot_20210826-141802_Discord](https://user-images.githubusercontent.com/83353462/130932330-75dee0bd-de4d-46ba-885e-a34e050e5121.jpg)
![Screenshot_20210826-135204_Discord](https://user-images.githubusercontent.com/83353462/130932335-761719d8-e415-4e86-aba0-d2bb9d5c9738.jpg)
E

**Comment by Gorott** [comment]
works
