### ISSUE TITLE
Mort can watch before night 2

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#259]
![Screenshot_20210827-131648_Discord](https://user-images.githubusercontent.com/83353462/131095461-4cacb8a4-6a01-48cc-99f5-1ca391dad7bb.jpg)

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
