### ISSUE TITLE
Make a cancel command for ranked games 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#267]

**Comment by FinnyMarigold58** [comment]
So something like +rwcancel?

**Comment by thewilloftheshadow** [comment]
Correct

**Comment by inno14** [comment]
Actually i say when we make then we should rename `+cancel ` to `+gwcancel ` 
So `+gwcancel ` will be used to cancel normal games
`+rwcancel ` for ranked games
This will also match dyno commands.
