### ISSUE TITLE
Lm reveal doesn't work.

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#278]

**Comment by inno14** [comment]
![Screenshot_20210927-144201_Discord](https://user-images.githubusercontent.com/83353462/134879659-3778b412-a12b-49c5-ad44-e627e9fb9fc0.jpg)
![Screenshot_20210927-144152_Discord](https://user-images.githubusercontent.com/83353462/134879673-169d842b-55db-475f-8707-1f6fc2d76291.jpg)

**Comment by 3061LRTAGSPKJMORMRT** [comment]
This should be fixed since the bot's code has been rewritten
