### ISSUE TITLE
Bandit

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#28]

**Comment by inno14** [comment]
Interactions of Bandit (Unknown)
- Bandit can't be killed by werewolves .
- They can convert his lover.
- They kills cursed / sect member on the attempt to convert them.
- They can't convert headhunter's target , werewolves, solo killers , cursed and protected people.
- They can't bypass protection. 
- Bandit can only convert Village-aligned role and Solo voters.
- Bandit will kill Sected, Bitten or Headhunter's target villager when trying to convert. 
- Bandit will kill Werewolves and Solo killers when trying to convert.
- Bandit can only have one accomplice at a time. 
- Bandit against Jailer in 1 v 1 situation will be instant win for Bandit.

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
