### ISSUE TITLE
if bh trap n1, kww scratch bh, bh gets turned

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#284]
![Screenshot_20210927-231642_Discord](https://user-images.githubusercontent.com/83353462/134959402-b0b55d21-97d2-42e4-a8e6-0a23fe2dcc74.jpg)
![Screenshot_20210927-231637_Discord](https://user-images.githubusercontent.com/83353462/134959412-1ca2f8dc-5a3c-438b-aa18-ef3381b61df0.jpg)

**Comment by inno14** [comment]
These ss aren't of n1. Cuz we forgot to click it.

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
