### ISSUE TITLE
Bodyguard didnt get bitten when 2 zombies try to bite bg

### ISSUE THREAD

**Issue by coolness2punkt0** [wwosimulation/tracker#294]
![image](https://user-images.githubusercontent.com/91492363/136076990-a9a28dca-85f6-4587-98a1-4f57f4f7e163.png)
![image](https://user-images.githubusercontent.com/91492363/136077048-84dc7668-e090-4dd5-bbb9-5935cfebff40.png)

**Comment by inno14** [comment]
Uh but in that case , if bg have shield then he should just lose the shield and zomb should fail (according to abbi and i feel so too)
