### ISSUE TITLE
Think of creating gitHub application

### ISSUE THREAD

**Issue by sampadap03** [wwosimulation/tracker#3]
<https://github.com/organizations/wwosimulation/settings/applications>

**Comment by thewilloftheshadow** [comment]
I have one for narrator bot, I'll transfer it over

**Comment by thewilloftheshadow** [comment]
The application page here is for oauth (“Sign in with GitHub”) which we don’t use/need

**Comment by sampadap03** [comment]
https://github.com/wwosimulation/wolvesville
I was referring to web application which is already done and hoisted on https://wwosimulation.github.io/wolvesville/
