### ISSUE TITLE
Bomber rewrite idea to make it more effective in all modes.

### ISSUE THREAD

**Issue by Garcello822** [wwosimulation/tracker#301]
At the moment, bomber can bomb 3 players in a row if 1 is alive. However, if you are in a 5 player game, 5 is unbombable because of their positioning. This makes bomber unviable in a number of cases because of low player count. I suggest that we make bomber more viable by rewriting the role concept and coding to be more similar to the original game.

Old: +bomb [player1 player2 player3]
New: +bomb [player]
- This sets a bomb on one player that extends to two people nearby. **You cannot set up a bomb on yourself.** After this bomb is set, it will display a message saying that you are bombing **[player], [playerToTheLeft], and [playerToTheRight]**. If these players don't exist, they will not be contained in the message. For instance, if you placed the bomb on 4, then only 3 and 4 would be bombed. There would not be an error message because 5 is not in the same row. Rather, the bomb would only apply to 3 and 4. If you bombed 4 and 3 is dead, then only 4 would be bombed. **Of course, the player that is bombed has to be alive.**

New: +rotate
After you have placed a bomb on a person, you can use +rotate to change the orientation of the bomb. For instance if you bombed 10, it would default to 9, 10, and 11 being exploded (the default orientation for the bomb). After you use rotate, the bomb will rotate clockwise. Now, 5, 10, and 15 will explode the following night. If you use it again, 6, 10, and 14 will explode the following night, etc.

New roleinfo:
At night, you can place a bomb on a living player by doing `+bomb [player]` which will explode during the the following night. You can change the direction of your bomb with `+rotate`. You cannot be killed by the werewolves. Your aura is **Unknown** and you are a **Solo** team player.

I hope I cleared everything up in this message, if not I'll be watching this issue for feedback and status (if it gets accepted).

**Comment by thewilloftheshadow** [comment]
ngl, I don’t like the idea of bomber in sim at all, because we don’t have any kind of grid or anything to base off of

This is currently what we check bomb placements against:
```module.exports.bombPlacements = ["1 2 3", "2 3 4", "5 6 7", "6 7 8", "9 10 11", "10 11 12", "13 14 15", "14 15 16", "1 5 9", "5 9 13", "2 6 10", "6 10 14", "3 7 11", "7 11 15", "4 8 12", "8 12 16", "1 6 11", "2 7 12", "3 6 9", "4 7 10", "5 10 15", "6 11 16", "7 10 13", "8 11 14"]
```
https://github.com/wwosimulation/config/blob/main/src/index.js#L44

If there is a way to completely do the role to where you don’t have to visualize a grid of people, im all for that.
As it is with this suggestion, I'll think on it

**Comment by Garcello822** [comment]
Balance idea number 1: if nobody is blown up through interactions, the bomb you place the next night will go off at the end of the same night.
Also these bombs are protectable but a doc that protects a bombed player will blow up and the bombed player will survive.

**Comment by Garcello822** [comment]
Actually i really like this idea

**Comment by Hackante** [comment]
better system in rewrite
