### ISSUE TITLE
Aura seer , doctor and witch can't use the ability 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#302]
![Screenshot_20211011-190710_Discord](https://user-images.githubusercontent.com/83353462/136799488-f81ece1f-66cc-4860-a4eb-e1d04756e0ff.jpg)
![Screenshot_20211011-190719_Discord](https://user-images.githubusercontent.com/83353462/136799527-120c62e8-1629-4ba0-ba88-edbaebfacc87.jpg)

**Comment by Garcello822** [comment]
also witch cant either (no ss)

**Comment by thewilloftheshadow** [comment]
Forgot to update the bot
