### ISSUE TITLE
Simplify day and night commands

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#312]
Right now, the day and night commands are very very long and repetitive, and this needs to be simplified.
This issue is what I will be using to track progress on this rewrite.

**Comment by thewilloftheshadow** [comment]
# Current list of the day command's actions:

## Initalize

- Require all the private channels into maps
- Require dayCount, nightCount
- Require alive, dead, trainee, narrator roles
- Initalize
  - cupidKilled as boolean
  - killedplayers as array
  - thekiller as array
  - hhtarget as array
  - drc as undefined
- Set variables
  - soloKillers
  - strongww (werewolf strength order)
  - village (village roles)

## Actions
### Small Actions
- Delete dreamcatcher's temporary private channel for their stolen role
- "Getting the dc their channel"?
- Unlock all private channels for users with the alive role
- "Setting the hh target"
- Give forged shield or sword
- Remove all kills if peace is activated
  - Bandit
  - Bandits(?)
  - Bandit(?)
  - Hacker
  - Cannibal
  - Serial Killer
  - Werewolf (Setting args[0] to "0")
### Hacker (forEach hacker from private channel)
- Get hacker channel
- Get hacker
- If secondhack_chan
  - forEach secondhack (referenced here as hacked)
    - guy = find hacked (hacked is number nickname)
    - if guy is alive    
      - Check BH trap
        - If trap triggered, cancel kill, too strong
        - If trap triggered, tell bh
      - Check jailer protection
        - If protected and guy is alive, tell hacker no kill
      - Check doctor protection
        - If protected, tell hacker and doctor
      - Check witch protection
        - If protected, tell hacker and witch
      - Check shield protection
        - If protected, tell hacked and hacker
      - Check bodyguard protection
        - If protected and bg has 2 lives
          - Tell bodyguard and hacker
          - Set lives to 1 for bg
        - If protected and bg has 1 life
          - Hack bg instead of hacked
            - Switch dead and alive roles
            - Send dayChat message
            - Push bg ID to killedplayers
            - Push hacker ID to thekiller
        - If hacked is bodyguard
          - If protected and bg has 2 lives
            - Tell bodyguard and hacker
            - Set lives to 1 for bg
          - If protected and bg has 1 life
            - Hack bg instead of hacked
              - Switch dead and alive roles
              - Send dayChat message
              - Push bg ID to killedplayers
              - Push hacker ID to thekiller
      - Check tough guy protection
        - if hacked role is tough guy
          - Tell hacker hacked can't be killed
          - Tell hacker hacked is tg and knows role
          - Tell hacked that they were hacked by the hacker
        - if protected
          - Tell hacker hacked can't be killed
          - Tell hacker hacked is tg and knows role
          - Tell hacked that they were hacked by the hacker
      - Check role is red lady. If it is,
        - Send "someone tried to kill you while you were away" message
        - Tell hacker hacked can't be killed
      - Kill player
        - If hacker is hyponotised
          - dayChat: "The dreamcatcher compelled the hacker to hack..."
        - else
          - dayChat: "The hacker hacked..."
        - If hacked is cupid
          - Set cupidKilled to true
        - Toggle dead and alive roles
        - Push hacked ID to killedplayers
        - Push hacker ID to thekiller
  - Set secondhack_chan to 0
### Cannibal (forEach cannibal from private channel)
- Get cannibal channel
- Get cannibal
- If no bite
  - Add one hunger
- If bite
  - forEach bitten
    - If bitten is alive
      - Check bh protection
      - Check jailer protection
      - check doc protection
      - Check witch protection
      - Check forger protection
      - Check bodyguard protection
      - Check tg protection
      - Check red lady protection
      - Kill player
        - dayChat: Cannibal ate user (or dreamcatcher)
        - If hacked is cupid
          - Set cupidKilled to true
        - Toggle dead and alive roles
        - Push bitten ID to killedplayers
        - Push cannibal ID to thekiller
        - Subtract 1 hunger
  - Add one hunger (?)
  - Set eat to null

*Finished through line 725 as of October 12*

**Comment by thewilloftheshadow** [comment]
I hate this

**Comment by Hackante** [comment]
closed with https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381
