### ISSUE TITLE
I'm not even going to explain this

### ISSUE THREAD

**Issue by Garcello822** [wwosimulation/tracker#324]
![image](https://user-images.githubusercontent.com/87214822/137610070-14f9978a-ea0b-4715-94ef-2372609731ef.png)

**Comment by Garcello822** [comment]
![image](https://user-images.githubusercontent.com/87214822/137610084-97c6b9f7-fc4f-4c0a-bfbf-19e9fbdef456.png)

**Comment by inno14** [comment]
https://discord.com/channels/465795320526274561/861979564514082876/899140238151127081

**Comment by thewilloftheshadow** [comment]
Fixed, bot didn't like the emoij in #joined
