### ISSUE TITLE
BH trap doesnt get removed when the target dies 

### ISSUE THREAD

**Issue by Accio-Aquamarine** [wwosimulation/tracker#327]
![image](https://user-images.githubusercontent.com/92143675/138066426-5be5e2b4-a5b6-467a-8e47-0da7582830bc.png)
trap was on 3

**Comment by Garcello822** [comment]
This isn't a bug what

**Comment by Garcello822** [comment]
why is this labeled as a bug

**Comment by Garcello822** [comment]
@thewilloftheshadow this isn't a bug, can you pull a reverse on all the progress made on this?

**Comment by Garcello822** [comment]
wrong ping @Accio-Aquamarine

**Comment by thewilloftheshadow** [comment]
Ahhh spammm. Wdym its not a bug

**Comment by Garcello822** [comment]
this is the way bh works in app

**Comment by Garcello822** [comment]
the trap is supposed to stay on

**Comment by thewilloftheshadow** [comment]
oh thats an easy fix

**Comment by Garcello822** [comment]
awesome, thanks!
