### ISSUE TITLE
MM cannot shoot on following night

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#336]
![Screenshot_20211028-223822_Discord](https://user-images.githubusercontent.com/83353462/139302744-d5f98e1b-a2e4-44ea-a1ae-c1d8cf6994d2.jpg)

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
