### ISSUE TITLE
Tough guy doesn't get info post-attack

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#34]

**Comment by inno14** [comment]
![Screenshot_20220107-143238_Discord](https://user-images.githubusercontent.com/83353462/148519662-4d230d23-8769-4ebc-9f66-da80b104f2ff.jpg)
I think close this

**Comment by inno14** [comment]
![Screenshot_20220107-143442_Discord](https://user-images.githubusercontent.com/83353462/148519759-e894d7da-936e-431e-b6b2-06529516ed65.jpg)
