### ISSUE TITLE
Everything in setTimeout (line 193) in night command doesnt work

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#340]
![Screenshot_20211029-165615_Discord](https://user-images.githubusercontent.com/83353462/139427908-1c02c44c-d5b8-4a18-aab0-6e35464481e6.jpg)
![Screenshot_20211029-165626_Discord](https://user-images.githubusercontent.com/83353462/139427916-3246dc79-71b9-48b2-b8c6-54f30f801ca7.jpg)

**Comment by Gorott** [comment]
Corr also doesnt work probably same reasonas dc

**Comment by Gorott** [comment]
Jailer, corr, dc, tg, alchemist, marksman, nmww, bandit and bomber all wont work during day to night cycle
