### ISSUE TITLE
+cancel cannot cancel ranked game

### ISSUE THREAD

**Issue by Accio-Aquamarine** [wwosimulation/tracker#343]

**Comment by Garcello822** [comment]
hey aqua, this was a highly specific contexted bug. It's irregular for sure, and it had something to do with commands that were supposed to go to ranked game getting posted in game announcements instead. I think the issue at the very least needs a rename
- Kirbs (host of the game that provided this bug)

**Comment by Accio-Aquamarine** [comment]
sure @Garcello822, that's great! Can you specify how it has occured? or any details if you want to add

**Comment by Garcello822** [comment]
I don't know how it occured, but here's some details.
The first rolelist was generated in day chat. So i deleted channels and rerolled. After that i started game which apparently posted in game announcements instead of ranked. From there, reset also posted in the wrong channel.

**Comment by thewilloftheshadow** [comment]
We never fully switched the bot into using a separate channel for ranked games because we didn't have a ranked season running for a while

**Comment by inno14** [comment]
Just saying, we have rwcancel for ranked games

Also i suggest that we should make reset and startgame different for ranked games **or** they send the output in #ranked-games when rwhost (ranked game) was used
