### ISSUE TITLE
[Bug]: Win streak should get lost when you loose

### ISSUE THREAD

**Issue by Hackante** [wwosimulation/tracker#351]
### What happened?

![image](https://user-images.githubusercontent.com/85803963/140516391-468de4a7-add6-456f-b22b-f8579a9828f1.png)
When you loose a game your win streak should get lost

### What part of the bot are you seeing the problem on?

Game - Player

### Game Code

T-T

**Comment by thewilloftheshadow** [comment]
Oh my gosh I'm such an idiot 😂😂 
I forgot to finish implementing that
