### ISSUE TITLE
Rose wheel check for enough roses fails

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#352]
### What happened?

Gmo used the +rosewheel command without 30 roses and it charged him, causing him to have negative roses.

### What part of the bot are you seeing the problem on?

Economy

**Comment by thewilloftheshadow** [comment]
I may have accidentally fixed this already, but needs testing

**Comment by Gmo666** [comment]
Also pay 30 roses to get 5 roses scam

**Comment by Hackante** [comment]
![image](https://user-images.githubusercontent.com/85803963/140606781-a7099584-5666-4829-b69b-ccc838ee8d76.png)
cannot reproduce

**Comment by thewilloftheshadow** [comment]
https://discord.com/channels/465795320526274561/606123806490230784/906571695261896744

**Comment by inno14** [comment]
Shouldn't this be closed as it is in "Complete" board ?

**Comment by Hackante** [comment]
Yep. The bug was not produced by the code but for some reason it was the the one process that didn't work
