### ISSUE TITLE
Avenger selected someone but they didn't die 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#356]
### What happened?

A bug happened!

### What part of the bot are you seeing the problem on?

Game - Player

### Game Code

After long time :)

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
