### ISSUE TITLE
Profile doesn't count losses 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#357]
### What happened?

![Screenshot_20211216-143509_Discord](https://user-images.githubusercontent.com/83353462/146341919-12a8f470-69ee-4678-9ebc-ed8c5a72c684.jpg)
Altra lost the game but have losses as 0 

### What part of the bot are you seeing the problem on?

Economy

### Game Code

Bishop

**Comment by Hackante** [comment]
This isn't an actual bug. It wasn't coded yet
