### ISSUE TITLE
Corrupted person doesn't die at the end of Day 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#358]
### What happened?

![Screenshot_20211216-153729_Discord](https://user-images.githubusercontent.com/83353462/146351536-b50638c9-59db-4fdf-90a5-311a7fa631ca.jpg)

### What part of the bot are you seeing the problem on?

Game - Player

### Game Code

Hunt

**Comment by Garcello822** [comment]
Bug known and reported, existing GitHub issue already

**Comment by inno14** [comment]
Ah ok so closed as duplicate of #340
