### ISSUE TITLE
Bombed players don't die by explosion 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#359]
### What happened?

![Screenshot_20211216-153831_Discord](https://user-images.githubusercontent.com/83353462/146351735-fc073df4-75cf-44dd-8899-7df9bee0b745.jpg)

### What part of the bot are you seeing the problem on?

Game - Player

### Game Code

Hunt

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
