### ISSUE TITLE
Cancel doesn't work 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#361]
### What happened?

I used bye in gs and then cancel in sim but then it replied 
![Screenshot_20211220-192608_Discord](https://user-images.githubusercontent.com/83353462/146778356-538bb5f5-0259-40eb-90b1-b3f0367b888c.jpg)

### What part of the bot are you seeing the problem on?

Game - Narrator

### Game Code

Zombd

**Comment by Hackante** [comment]
`+bye` ends the game (deletes it) `+cancel` announces the cancel and deletes the game (only if a game exists)
Use `+cancel` first then `+bye`
