### ISSUE TITLE
vt broken ig

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#364]
### What happened?

![Screenshot_20211227-164058_Discord](https://user-images.githubusercontent.com/83353462/147466483-d4d3f21d-8574-4573-aa77-46e2a07256dd.jpg)

### What part of the bot are you seeing the problem on?

Game - Narrator

### Game Code

Requested by Kanna, hosted by Kanna

**Comment by Hackante** [comment]
![image](https://user-images.githubusercontent.com/85803963/162427741-7b6b0b65-a088-4efa-a1cb-213f3d632dfb.png)
probably wrong usage of `+day` => `+day 0`
