### ISSUE TITLE
Vigilante

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#365]
### What is your suggestion?

![Uploading Screenshot_20211229-191410_Discord.jpg…]()

### Where is this suggestion from?

Other

**Comment by inno14** [comment]
https://discord.com/channels/465795320526274561/859099353985974292/924971682928681000

**Comment by Hackante** [comment]
vigilante:
reveal - :whistle: shoot - :bullet: 
reveal role on shoot; precedence doesn't matter

**Comment by Hackante** [comment]
[Icon](https://cdn.discordapp.com/emojis/923194555732459551.png?v=1)
During the day you can either shoot gunner or reveal loudmouth another player. Both actions can only be done once, but not during the same day. Your aura is Unknown and you belong to the Village team.
