### ISSUE TITLE
Suicide safety question

### ISSUE THREAD

**Issue by Hackante** [wwosimulation/tracker#367]
### What is your suggestion?

When a player types `+suicide` there shoule be a safety question like in the app. I've seen a couple of players who sent `+suicide 2` or something similar and died, because the code doesn't check for more arguments here.

The message would look like this: 
![image](https://user-images.githubusercontent.com/85803963/147991582-738d1c19-86be-4822-9280-61c87305d3b4.png)

### Where is this suggestion from?

Dev Assistant

**Comment by thewilloftheshadow** [comment]
Go for it
