### ISSUE TITLE
Fortune Teller able to run the +give command more then twice

### ISSUE THREAD

**Issue by coolness2punkt0** [wwosimulation/tracker#369]
### What happened?

Fortune Teller run the +give command more then twice and all people also got a card then.

### What part of the bot are you seeing the problem on?

Game - Narrator

### Game Code

:wumpus_swag:

**Comment by coolness2punkt0** [comment]
![image](https://user-images.githubusercontent.com/91492363/148109307-743060e1-f3d8-4b1b-aa8a-46fd09729f50.png)

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
