### ISSUE TITLE
Add aliases to +roleinfo

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#37]
If anyone would like to help compile a list, that would be much appreciated

**Comment by inno14** [comment]
> If anyone would like to help compile a list, that would be much appreciated

How can i help to do so? ~~idk so asking~~

**Comment by inno14** [comment]
@thewilloftheshadow ^

**Comment by inno14** [comment]
Aura-seer: aura
Avenger: ave
Beast-hunter: bh
Bodyguard: bg
Cursed: cursed 
Detective: det
Doctor: doc
Flower-child: fc
Forger: forger 
Fortune-teller: ft
Grave-robber: gr
Grumpy-grandma: gg

**Comment by Gmo666** [comment]
sorcerer is sorc

**Comment by inno14** [comment]
Aura-seer: aura
Avenger: ave
Beast-hunter: bh
Bodyguard: bg
Cursed: cursed
Detective: det
Doctor: doc
Flower-child: fc
Forger: forger
Fortune-teller: ft
Grave-robber: gr
Grumpy-grandma: gg
Gunner: gunner
Jailer: jailer
Loudmouth: lm
Marksman: mm
Mayor: Mayor
Medium: med
Pacifist: paci
President: pres
Priest: priest
Red-lady: rl
Seer: seer
Seer-apprentice: seer app
Spirit-seer: ss
Sheriff: Sheriff
Tough-guy: tg
Villager: forkman , fork
Witch: witch
Santa-claus: santa
Easter-bunny: easter
Cupid: Cupid

Alpha-werewolf: Alpha, aww
Guardian-wolf: guardian , gww
Junior-werewolf: jww
Kitten-wolf: kww , Kitten
Shadow-wolf: sww, shadow
Sorcerer:
Werewolf: ww
Werewolf-berserk: wwb , bww , berserk
Wolf-pacifist: wolf paci , wwp
Wolf-shaman: shaman
Wolf-seer: wws

Alchemist: alc
Arsonist: arso
Bomber: bb
Corruptor: corruptor
Illusionist: illu
Serial-killer: sk
Bandit: bandit
Accomplice: acc
Sect-leader: sl
Sect-member: sm
Zombie: Zombie
Fool: fool
Headhunter: hh
Random regular villager: rrv
Random strong villager: rsv
Random Werewolf: rww
Random voting: rv
Random killer: rk
