### ISSUE TITLE
Booster using lootbox gets double coins

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#375]
### What happened?

![Screenshot_20220105-160249_Discord](https://user-images.githubusercontent.com/83353462/148203342-bfd34ea0-b14e-4cd5-9b29-5521066da371.jpg)

### What part of the bot are you seeing the problem on?

Economy

**Comment by Hackante** [comment]
![image](https://user-images.githubusercontent.com/85803963/148618610-c8e8561f-1ca4-4088-9529-723d60add903.png)
Bit different but but fixed anyways
