### ISSUE TITLE
+reset doesn't remove perms from ww from ww channel

### ISSUE THREAD

**Issue by coolness2punkt0** [wwosimulation/tracker#376]
### What happened?

I used +reset before the game started and the perms for the ww didnt got removed.

### What part of the bot are you seeing the problem on?

Game - Narrator

### Game Code

another one :)

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
