### ISSUE TITLE
Sect leader 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#377]
Interactions of Sect Leader (Unknown) 
- They can be killed by werewolves. 
- Sect members doesn't die if sect leader commits suicide. 
- They can't bypass protection.
- They can't convert solo killer, werewolves and headhunter's target.
- Sect leader is a unique role.
- Sect leader can only convert village-aligned roles and Solo voter.
- Sect leader will not know the role of the sect members.
- Sect members can see the other sect members.
- If Sect leader dies, all sect member will die.
- Sect leader against Jailer in 1 v 1 situation will be instant win for Sect leader.
 

Also , if possible when recode sect then change #sect-members to #sect-team so that the channel name makes more sense cuz sect leader also see the channel and not only sect members.

**Comment by Hackante** [comment]
closed with https://github.com/wwosimulation/Narrator-bot/pull/370
