### ISSUE TITLE
Grave robber 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#378]
Interactions of Grave Robber (Random Regular Villager - Good)
- Grave robber cannot be Headhunter’s target.
- Grave robber cannot have the following roles as the target: Mayor, Flower Child, Pacifist, Cursed, Jailer, Marksman, Cupid, Medium, Seer, Seer apprentice, Detective, President, Kitten Wolf, Wolf Pacifist, Wolf seer, Sect Leader, Zombie, Bandit and Headhunter
- Grave robber can only use the role's leftover abilities. e.g. If Fortune teller has only 1 card when they died, Grave Robber can only give 1 card.

**Comment by Hackante** [comment]
closed with https://github.com/wwosimulation/Narrator-bot/pull/370
