### ISSUE TITLE
Sorcerer couldn't check anyone 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#379]
### What happened?

A bug happened!

### What part of the bot are you seeing the problem on?

Game - Player

### Game Code

: astral_wolf :

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
