### ISSUE TITLE
Red lady can not visit 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#384]
### What happened?

![Uploading Screenshot_20220109-163033_Discord.jpg…]()

### What part of the bot are you seeing the problem on?

Game - Player

### Game Code

wohoo

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
