### ISSUE TITLE
Upgrade Discord to v13.5.1

### ISSUE THREAD

**Issue by Hackante** [wwosimulation/tracker#386]
Embeds with functions (like .setTitle()) are deprecated now. Everything should be done as an object in the embed

**Comment by thewilloftheshadow** [comment]
They're not depreciated? Where did you see that?

**Comment by Hackante** [comment]
When I started the bot on discord v13.5.1 a deprecated warning was given out 
![image](https://user-images.githubusercontent.com/85803963/148821264-d61741e9-cfca-4766-870f-e07f2dbbc627.png)
I just looked at change logs and only setAuthor() and setFooter seems to be dep

**Comment by thewilloftheshadow** [comment]
It's only depreciating directly passing a string. Instead, you need to do this:
```js
embed.setAuthor({name: "text here"})
embed.setFooter({text: "text here"})
```
