### ISSUE TITLE
New XP system

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#39]

**Comment by Gmo666** [comment]
**Game Result**
Winning: 4 x (Number of players) x (Team Multiplier) xp
Losing: 4 x (Number of players) xp
*XP for all players is halved in a game with more than 50% roles as solo.*
__Team Multiplier__
Village: 3
Werewolves: 4
Couple/Sect/Zombie/Bandits/Fool/Headhunter: 5
Solo Killer: 6
**Streak**
2 games in a row - 10 xp
3 games - 20 xp
4 games - 40 xp
5 games - 70 xp
6+ games - 100 xp 
**Miscellaneous**
First Win of the Day: 80 xp
**Quests**
Easy: 40 xp
Medium: 80 xp
Hard: 120 xp
Special: Varies
Mega: Varies (Usually 200/120/60)
