### ISSUE TITLE
Bot didn't give color role... again

### ISSUE THREAD

**Issue by FinnyMarigold58** [wwosimulation/tracker#393]
### What happened?

Well just like #300 looks like the fix didn't work.

Proof:
![Picture of Purchase](https://cdn.e-z.host/e-zimagehosting/c64fc26f-d472-4eae-9618-a6079e01cd42/5ec6a603.png)
![Picture of my roles](https://cdn.e-z.host/e-zimagehosting/c64fc26f-d472-4eae-9618-a6079e01cd42/77b610f4.png)

### What part of the bot are you seeing the problem on?

Economy

### Game Code

N/A

**Comment by Hackante** [comment]
As mentioned in #300 this will be fixed in wwosimulation/Narrator-bot#211
