### ISSUE TITLE
Rl visiting evil on n2 ,  didn't die

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#399]
### What happened?

A bug happened!

### What part of the bot are you seeing the problem on?

Game - Player

### Game Code

We have 2 abbi

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
