### ISSUE TITLE
Unlock didn't delete messages in #vote-chat on d3

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#400]
### What happened?

A bug happened!

### What part of the bot are you seeing the problem on?

Game - Narrator

### Game Code

We have 2 abbi

**Comment by Hackante** [comment]
![image](https://user-images.githubusercontent.com/85803963/154820807-c76f4635-9952-48a3-8b62-6182680d00a8.png)
works again

**Comment by Hackante** [comment]
![image](https://user-images.githubusercontent.com/85803963/155986314-bb387179-5345-4aaf-bc42-da87c6458c5b.png)

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
