### ISSUE TITLE
7 could view ww chat as dead by corruptor 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#402]
### What happened?

A bug happened!
![Screenshot_20220116-182554_Discord](https://user-images.githubusercontent.com/83353462/149663572-4556cfb9-7409-4093-bbe4-68f55c353b4a.jpg)

### What part of the bot are you seeing the problem on?

Game - Player

### Game Code

We have 2 abbi

**Comment by Gorott** [comment]
This is probably related to server perms and not the bot

**Comment by inno14** [comment]
![Screenshot_20220120-151145_Discord](https://user-images.githubusercontent.com/83353462/150313569-83c2c6d8-6323-46c9-bc8c-dbf818ad0757.jpg)
Nope

**Comment by Hackante** [comment]
Can you please recreate a situation like this? Currently everything in the code makes sense and it was probably a one time thing

**Comment by inno14** [comment]
Sure we can try

**Comment by Hackante** [comment]
will be closed with #404
