### ISSUE TITLE
Preacher 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#413]
### What is your suggestion?

His action emoji 
![Screenshot_20220129-105454_Discord](https://user-images.githubusercontent.com/83353462/151648719-cfd25a22-4bf0-4d95-82f2-207e35e981d5.jpg)

### Where is this suggestion from?

Other

**Comment by Hackante** [comment]
When a villager is lynched, you gain one extra vote. Activate your ability to use the extra votes during the day. Once used, you lose your extra votes. Your aura is Good and you belong to the Village team.
