### ISSUE TITLE
can't use +day 0 even tho ww have died

### ISSUE THREAD

**Issue by Oops-Abbi** [wwosimulation/tracker#422]
### What happened?

bh, avg, and canni was left and ww specifically gww was voted out already. And bot didn't allow day 0

### What part of the bot are you seeing the problem on?

Game - Narrator

### Game Code

game code: cuz carl said so
![image](https://user-images.githubusercontent.com/98696089/153750592-8a912409-1bf4-4201-99c1-4cba3e9fc32c.png)

**Comment by Hackante** [comment]
It would be helpful if you could test this a bit more to get more specific when it bugs. The day file is more than 3800 lines so the error would be very hard to find

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
