### ISSUE TITLE
Easter bunny 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#423]
### What is your suggestion?

Things should happen!

### Where is this suggestion from?

Other

**Comment by Hackante** [comment]
You are a villager who only appears during the Easter time. Each night you automatically send a greeting to all players. Additionally you can gift a special item to a dead but still connected player. Give up to 4 gifts to dead players. These gifts have no further effect on the game! Your aura is Good and you belong to the Village team.
