### ISSUE TITLE
Baker

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#424]
### What is your suggestion?

Things should happen!

### Where is this suggestion from?

Other

**Comment by Hackante** [comment]
Each night you can select a player to give them bread, giving them an extra vote for the next day. Your aura is Good and you belong to the Village team.

**Comment by Hackante** [comment]
✔️ Coded 
✔️ Merged into [new-roles](https://github.com/wwosimulation/Narrator-bot/tree/new-roles)
❌ Waiting for more roles + testing
