### ISSUE TITLE
You can only sent one bouquet at a time

### ISSUE THREAD

**Issue by coolness2punkt0** [wwosimulation/tracker#429]
### What happened?

A bug happened!

### What part of the bot are you seeing the problem on?

Economy

**Comment by coolness2punkt0** [comment]
![image](https://user-images.githubusercontent.com/91492363/154708998-226c7d7e-beae-42e1-bbe3-0027aaf8c1f0.png)

**Comment by Hackante** [comment]
this isn't a bug. It is meant to be one bouquet at the time (see `+help rose`)
