### ISSUE TITLE
+suicide triggered gamewarn message

### ISSUE THREAD

**Issue by coolness2punkt0** [wwosimulation/tracker#431]
### What happened?

Narrator killed a player with +suicide and gamewarn message was triggered

### What part of the bot are you seeing the problem on?

Game - Narrator

### Game Code

uez

**Comment by Hackante** [comment]
which suicide message? I am pretty sure it is wanted

**Comment by inno14** [comment]
> which suicide message? I am pretty sure it is wanted

When a narr kills someone in #day-chat
~~replying here in case you missed in discord~~

**Comment by Gorott** [comment]
That is wanted right? Just to remind the narr to warn the player if needed

**Comment by Hackante** [comment]
Yes. This message is intended to appear for the reason groot told. It will be removed when narrators got to know the warn system for a while

**Comment by inno14** [comment]
Maybe close it then

**Comment by Hackante** [comment]
We will let this open till it is actually removed. In about 2-3 weeks ig
