### ISSUE TITLE
RL doesn't die when visiting alchemist

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#44]

**Comment by sampadap03** [comment]
Oh, I forgot this got assigned. If RL visits an alchemist they should die. It was something like that in #bug-reports. let me confirm again.

**Comment by sampadap03** [comment]
https://discord.com/channels/465795320526274561/608673097058353164/845245377635549215

**Comment by inno14** [comment]
Multiple rl not just 1 rl

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
