### ISSUE TITLE
TO DO: Make all actions into startgame.js instead of srole

### ISSUE THREAD

**Issue by 3061LRTAGSPKJMORMRT** [wwosimulation/tracker#460]
- some narrators use `+manual` for testing, and not srole
- this leads to srole not being used, and the database declaration might not be accurate
- srole is only suppose to give roles, as it stands for shuffle-roles
- startgame is where we are suppose to "start" the game, so all action related should start there.

**Comment by Hackante** [comment]
@3061LRTAGSPKJMORMRT did you do this in the rewrite?

**Comment by 3061LRTAGSPKJMORMRT** [comment]
Yup. Closing since this is done
