### ISSUE TITLE
Original zombie dies at end of 3 nights 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#478]
### What happened?

A bug happened!
Ik ashish will fix it but just posted it here so that we don't forget to test it once he complete .

### What part of the bot are you seeing the problem on?

Game - Player

### Game Code

Uh

**Comment by Hackante** [comment]
This issue might be outdated and fixed in https://github.com/wwosimulation/Narrator-bot/pull/370 or https://github.com/wwosimulation/Narrator-bot/pull/381 
If the problem persists, please create a new issue.
