### ISSUE TITLE
Add a rose wheel

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#70]

**Comment by inno14** [comment]
How do we add a tag ? 
~~I think i can't add but why not ask it 😂😂🤣🤣~~

**Comment by thewilloftheshadow** [comment]
Only me and Aqua can

**Comment by inno14** [comment]
Ah ok

**Comment by thewilloftheshadow** [comment]
https://wovsim.theshadow.xyz/rosewheel

**Comment by Hackante** [comment]
May I do this? I would add 1000 coins, 2x 200 coins 2x 400 coins, 1 lootbox an then we would have to replace the icon and skin part till they are implemented in the economy system.
But the prizes are not fixed. AS 1000 is very much

**Comment by thewilloftheshadow** [comment]
Go for it. I originally had made a testing site for a spinning wheel and stuff but never finished it

https://github.com/wwosimulation/config/blob/main/src/rosewheel.js
https://github.com/wwosimulation/rose-wheel

**Comment by Hackante** [comment]
@thewilloftheshadow what do we do when they win icons?

**Comment by thewilloftheshadow** [comment]
One gem
