### ISSUE TITLE
Db reset failed

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#74]
![Screenshot_20210625-154043_Discord](https://user-images.githubusercontent.com/83353462/123409856-4bff4f80-d5cc-11eb-86c8-f8adc8da6c07.jpg)
![Screenshot_20210625-154052_Discord](https://user-images.githubusercontent.com/83353462/123409864-4e61a980-d5cc-11eb-811a-710503d14a87.jpg)
 Sect leader couldn’t convert fool (2). Bodyguard received a message when this happened.

**Comment by inno14** [comment]
Also there was no bodyguard in the game.

Also the bot didn't gave any link neither it reported the bug. 
![Screenshot_20210625-154113_Discord](https://user-images.githubusercontent.com/83353462/123410017-781ad080-d5cc-11eb-842e-534fe11f1040.jpg)

**Comment by thewilloftheshadow** [comment]
Db failed to reset
