### ISSUE TITLE
+bug 5 jailed 3 , but 3 watered someone and died and could still see #.jailed-chat

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#79]
+bug 5 jailed 3 , but 3 watered someone and died and could still see #.jailed-chat

**Comment by inno14** [comment]
![Screenshot_20210626-160039_Discord](https://user-images.githubusercontent.com/83353462/123510181-be893180-d697-11eb-84c5-4636511ac7f9.jpg)
2 images ^^
![Screenshot_20210626-160051_Discord](https://user-images.githubusercontent.com/83353462/123510187-c21cb880-d697-11eb-99f6-fe306aac8951.jpg)

**Comment by 3061LRTAGSPKJMORMRT** [comment]
Already made a (possible) fix for it. Needs testing
